### PR TITLE
Remove useless eggs

### PR DESCRIPTION
**Pull request by jeffw16**
Let's be mature and remove these eggs. The product should be efficient and non-distracting to students, not egged up for Easter all school year. Add some subtle eggs and export these to somewhere else if you'd like, @champfish.

### CODE REVIEW

**Comment by jeffw16** [comment]
Umm no

**Comment by champfish** [comment]
We don't have to have a link to the eggs from the product. They are just cool things to show off to Ms. Moranza.

**Comment by jeffw16** [comment]
While they are cool, this is unfeasible for every time we clone this repo to our testing server. Let's just move it to another repo, plz. Thx

**Comment by jeffw16** [comment]
Already happened.

**Comment by champfish** [comment]
you could have at least given me a chance to save them somewhere.

**Comment by jeffw16** [comment]
They are available on https://github.com/pluma-lms/pluma-lms-php/tree/pre-nodejs-fork

**Pull request closed without merging**
